### ISSUE TITLE
Support for non-root users

### ISSUE THREAD

**Issue by ghost** [Hackebein/docker-srcds#2]
Hi, great work with those. For mounting reasons, I'm trying to run everything as a non-root user with a specified UID. My attempts at tweaking the image myself have been failures, so I'm turning to you to see what kind of changes this would require. Cheers!

**Comment by Hackebein** [comment]
I'll give that a try but I'm on vacation. Don't expect me to start it this week.

**Comment by ghost** [comment]
Of course! Thanks for looking into it. 👍

**Comment by birdhimself** [comment]
It would be great if the internal steam/server process would run as a non-root user at least. [This similar project](https://github.com/marcermarc/DockerSteam) creates a `steam` user for SteamCMD and srcds.

**Comment by Hackebein** [comment]
Ohh that is a good help for the start.

**Comment by ghost** [comment]
Hey, were you able to take a look to this?

**Comment by Hackebein** [comment]
Sorry for my late response. I totally forgot this request.

**Comment by Hackebein** [comment]
It's nearly done. It seem it's working. Can you try it out in your environment and use case?

known bugs:
* overlay folder configuration is not working

**Comment by Hackebein** [comment]
Can't find any bugs anymore. I would appreciate feedback.

**Comment by ghost** [comment]
Getting back to you asap. Thanks a bunch!

**Comment by ghost** [comment]
The server does run as my nonprivileged user. Thanks again, I guess this can be closed. :)

**Comment by ghost** [comment]
Found one, it would seem workshop downloads are failing (`Input/output failure!`). No problem when running as root.

**Comment by Hackebein** [comment]
Are you mounting your files in a persistent way? Did you change the owner of your persistent files to match with the user inside the container? Can you post how you start the container?

**Comment by ghost** [comment]
Sure thing.

`podman create --name ttt -e "AUTHKEY=x" -e "APPS=4020,232330" -e "GLSTAPP=4000" -e "GAME=garrysmod" -e "CUSTOMPARAMETERS=+gamemode terrortown +map ttt_bb_teenroom_b2 +host_workshop_collection x" -p 27015:27015/tcp --user 1000:1000 -dt hackebein/srcds:latest`

I did try mounting `/opt/steam` or `/opt/steam/garrysmod`, but as you can see it didn't matter.

**Comment by Hackebein** [comment]
I found the bug. It should be fixed in the next build (in ~20 Minutes).

Do you know there is an other image called `hackebein/garrysmod`? That would make your start command shorter and more clear. for example: `podman create --name ttt -e "AUTHKEY=x" -e "GAMEMODE=terrortown" -e "MAP=ttt_bb_teenroom_b2" -e "WORKSHOP=x" -p 27015:27015/tcp --user 1000:1000 -dt hackebein/garrysmod:latest`

Do you know RCON is not working until you add `-p 27015:27015/udp`?

**Comment by ghost** [comment]
I'm trying to build a generic image, I'm happy to tweak this one instead! I do not intend to use RCON.

**Comment by Hackebein** [comment]
Build is finished. What ever your plan is :D I hope it's working :)

I close this issue. Feel free to reopen when you heading another problem, what is related to this issue. Or open a new one.
