### ISSUE TITLE
FEATURE-REQUEST: Mounting

### ISSUE THREAD

**Issue by Jormodn** [Hackebein/docker-srcds#3]
Hey Lars,

hast du geplant das Mounting von anderen Servern in das srcds einzubauen? Ist manchmal ja Relevant( TTT, Gmod) andere Server für die Props einzubinden mittels mount.cfg.

Grüße

**Comment by Hackebein** [comment]
Der Container kann das bereits dynamisch. Soweit ich weiß benutzt das Mounting System nur Garry's Mod daher supportet dieser Docker Container es auch nur für Garry's Mod. Solltest du mehr Source Dedicated Server kennen die davon gebrauch machen, lass es mich wissen.
Die Funktionalität versteckt sich hier in diesen Zeilen (https://github.com/Hackebein/docker-srcds/blob/master/entrypoint.sh#L46-L59). In dem Garry's Mod Template sind mehrere App ID's eingetragen (https://github.com/Hackebein/docker-garrysmod/blob/master/Dockerfile#L5), hierdurch wird der CSS Content und der Garry's Mod Content herunter geladen und der CSS Content verweis in die `mount.cfg` und `mountdepots.txt` geschrieben. Wenn du mehr Source Spiele Content mit installieren möchtest, kannst du denn `APPS` Parameter erweitern z.B. mit `,222860` (Left 4 Dead 2 Dedicated Server), indem du den Docker Container mit `docker -e "APPS=4020,232330,222860" [...]` startest.

Alternative solltest du Content, der in die `mount.cfg`/`moundepots.txt` muss, über den Overlay Folder (z.B. `docker -v ./overlay:/opt/overlay [...]`) hinzufügen, musst dich auch selbst um die `mount.cfg`/`moundepots.txt` kümmern.

Erfülle ich deinen Feature Request damit?

**Comment by Hackebein** [comment]
Alternative solltest du Content, der in die `mount.cfg`/`moundepots.txt` muss, über den Overlay Folder (z.B. `docker -v ./overlay:/opt/overlay [...]`) hinzufügen, musst dich auch selbst um die `mount.cfg`/`moundepots.txt` kümmern

**Comment by Hackebein** [comment]
Erfülle ich deinen Feature Request damit?

**Comment by Jormodn** [comment]
Ja aber sowas von. Danke, hat mir geholfen. Läuft so wie du gesagt hast.

Riesen Dank
