### ISSUE TITLE
Crash when the /opt/overlay directory is empty

### ISSUE THREAD

**Issue by jstsddg** [Hackebein/docker-srcds#4]
In our kubernetes cluster the container crashes on startup, if the directory "/opt/overlay" is empty:
```
[...]
Success! App '4020' fully installed.
Copy overlay
cp: cannot stat '/opt/overlay/*': No such file or directory
```

We think the problem is in "entrypoint.sh" on line 160.

Image Version: `hackebein/garrysmod@sha256:c110c893db45d658fad8b594f3b45dc31468d1986f58739338e3805a4fbfcf15`

**Comment by Hackebein** [comment]
Thanks for reporting. I'll fix that immediately. It happens in my last [commit](https://github.com/Hackebein/docker-srcds/commit/a4e690d3b54c506d29403b5716bd593c7c92409c)

**Comment by Hackebein** [comment]
It's fixed in all images

**Comment by jstsddg** [comment]
Thanks for your help!
