### ISSUE TITLE
Add option to disable steamcmd validation

### ISSUE THREAD

**Issue by FlorianFreudiger** [Hackebein/docker-srcds#5]
An option to disable the steamcmd validation would be great, it would
- Reduce the startup time of the server, for example if you have to restart often to test changes.

- Allow changing downloaded files (e.g. files inside garrysmod/gamemodes) since the "-validate" option will discard changes.
I have tried mounting my changed files as read-only but steamcmd will then fail with error 0x602.
While a normal update to those files would still fail, the files I am changing haven't been modified in years and if they ever get updated I can reapply my changes myself.

**Comment by Hackebein** [comment]
> An option to disable the steamcmd validation would be great, it would
> 
> * Reduce the startup time of the server, for example if you have to restart often to test changes.

Good idea. I'll add that later in the day.

> * Allow changing downloaded files (e.g. files inside garrysmod/gamemodes) since the "-validate" option will discard changes.
>   I have tried mounting my changed files as read-only but steamcmd will then fail with error 0x602.
>   While a normal update to those files would still fail, the files I am changing haven't been modified in years and if they ever get updated I can reapply my changes myself.

I took already care about this option. You can mount your files into `/opt/overlay` to overwrite them. This files getting copied over on each start.
https://github.com/Hackebein/docker-srcds/blob/027608f52cee0377e0c3e3882495eda7f5ea4b32/entrypoint.sh#L160

**Comment by FlorianFreudiger** [comment]
In general it would be good to be able to adjust the steamcmd parameters, for example for users which like to install a different language

**Comment by FlorianFreudiger** [comment]
> >   I took already care about this option. You can mount your files into `/opt/overlay` to overwrite them. This files getting copied over on each start.
> >   https://github.com/Hackebein/docker-srcds/blob/027608f52cee0377e0c3e3882495eda7f5ea4b32/entrypoint.sh#L160

Thanks for the quick response, I missed those settings 👍 
(Maybe you could add it to the readme of docker-garrysmod)

**Comment by Hackebein** [comment]
> Maybe you could add it to the readme of docker-garrysmod

It's there. Not directly but it's there. In the last line of readme it says `You can found more configuration options on the parent image page hackebein/srcds`. It's only liked because i don't wanna copy&paste all possible options from readme to readme to readme.

**Comment by Hackebein** [comment]
app_update parameter got moved.

Thanks for the feedback :)
